export type CarMake = {
  id: string;
  en: string;
  ar: string;
  models: string[];
};

export const carYears = Array.from({ length: 2027 - 1990 + 1 }, (_, i) => String(2027 - i));

export const carMakes: CarMake[] = [
  {
    id: "toyota",
    en: "Toyota",
    ar: "تويوتا",
    models: [
      "Camry",
      "Corolla",
      "Corolla Cross",
      "Yaris",
      "Avalon",
      "Crown",
      "Land Cruiser",
      "Land Cruiser 70",
      "Prado",
      "FJ Cruiser",
      "4Runner",
      "Sequoia",
      "Tundra",
      "Hilux",
      "Fortuner",
      "RAV4",
      "Highlander",
      "Rush",
      "Raize",
      "Veloz",
      "Innova",
      "Hiace",
      "Granvia",
      "Coaster",
      "Supra",
      "GR86",
      "C-HR",
      "bZ4X",
    ],
  },
  {
    id: "lexus",
    en: "Lexus",
    ar: "لكزس",
    models: ["ES", "IS", "LS", "GS", "LC", "RC", "UX", "NX", "RX", "GX", "LX", "LM", "RZ", "TX"],
  },
  {
    id: "hyundai",
    en: "Hyundai",
    ar: "هيونداي",
    models: [
      "Accent",
      "Elantra",
      "Sonata",
      "Azera",
      "i10",
      "i20",
      "i30",
      "Veloster",
      "Creta",
      "Tucson",
      "Santa Fe",
      "Palisade",
      "Kona",
      "Venue",
      "Bayon",
      "Staria",
      "H-1",
      "Ioniq 5",
      "Ioniq 6",
    ],
  },
  {
    id: "genesis",
    en: "Genesis",
    ar: "جينيسيس",
    models: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  },
  {
    id: "kia",
    en: "Kia",
    ar: "كيا",
    models: [
      "Pegas",
      "Cerato",
      "K5",
      "K8",
      "Stinger",
      "Picanto",
      "Rio",
      "Soul",
      "Seltos",
      "Sonet",
      "Sportage",
      "Sorento",
      "Telluride",
      "Carnival",
      "Mohave",
      "Niro",
      "EV6",
      "EV9",
    ],
  },
  {
    id: "nissan",
    en: "Nissan",
    ar: "نيسان",
    models: [
      "Sunny",
      "Sentra",
      "Altima",
      "Maxima",
      "Tiida",
      "Patrol",
      "Patrol Safari",
      "Armada",
      "X-Terra",
      "X-Trail",
      "Pathfinder",
      "Navara",
      "Kicks",
      "Magnite",
      "Juke",
      "Qashqai",
      "Z",
      "GT-R",
      "Urvan",
    ],
  },
  {
    id: "infiniti",
    en: "Infiniti",
    ar: "إنفينيتي",
    models: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  },
  {
    id: "honda",
    en: "Honda",
    ar: "هوندا",
    models: ["City", "Civic", "Accord", "CR-V", "HR-V", "ZR-V", "Pilot", "Odyssey"],
  },
  {
    id: "gmc",
    en: "GMC",
    ar: "جي إم سي",
    models: ["Yukon", "Yukon XL", "Sierra", "Terrain", "Acadia", "Canyon", "Hummer EV"],
  },
  {
    id: "chevrolet",
    en: "Chevrolet",
    ar: "شيفروليه",
    models: [
      "Tahoe",
      "Suburban",
      "Silverado",
      "Colorado",
      "Malibu",
      "Impala",
      "Cruze",
      "Aveo",
      "Spark",
      "Captiva",
      "Traverse",
      "Blazer",
      "Trailblazer",
      "Groove",
      "Equinox",
      "Camaro",
      "Corvette",
    ],
  },
  {
    id: "cadillac",
    en: "Cadillac",
    ar: "كاديلاك",
    models: ["Escalade", "CT4", "CT5", "XT4", "XT5", "XT6", "Lyriq"],
  },
  {
    id: "ford",
    en: "Ford",
    ar: "فورد",
    models: [
      "Taurus",
      "Explorer",
      "Expedition",
      "Everest",
      "Edge",
      "Escape",
      "Territory",
      "Bronco",
      "Ranger",
      "F-150",
      "Mustang",
      "Figo",
    ],
  },
  {
    id: "dodge",
    en: "Dodge",
    ar: "دودج",
    models: ["Charger", "Challenger", "Durango"],
  },
  {
    id: "jeep",
    en: "Jeep",
    ar: "جيب",
    models: ["Wrangler", "Gladiator", "Grand Cherokee", "Cherokee", "Compass"],
  },
  {
    id: "ram",
    en: "Ram",
    ar: "رام",
    models: ["1500", "2500"],
  },
  {
    id: "mercedes",
    en: "Mercedes-Benz",
    ar: "مرسيدس",
    models: [
      "A-Class",
      "C-Class",
      "E-Class",
      "S-Class",
      "CLA",
      "CLS",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "G-Class",
      "AMG GT",
      "SL",
      "V-Class",
      "EQE",
      "EQS",
    ],
  },
  {
    id: "bmw",
    en: "BMW",
    ar: "بي إم دبليو",
    models: [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "7 Series",
      "8 Series",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "XM",
      "Z4",
      "i4",
      "i5",
      "i7",
      "iX",
    ],
  },
  {
    id: "audi",
    en: "Audi",
    ar: "أودي",
    models: ["A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8", "e-tron", "TT", "R8"],
  },
  {
    id: "porsche",
    en: "Porsche",
    ar: "بورشه",
    models: ["911", "718 Cayman", "718 Boxster", "Panamera", "Cayenne", "Macan", "Taycan"],
  },
  {
    id: "land-rover",
    en: "Land Rover",
    ar: "لاند روفر",
    models: [
      "Range Rover",
      "Range Rover Sport",
      "Range Rover Velar",
      "Range Rover Evoque",
      "Defender",
      "Discovery",
      "Discovery Sport",
    ],
  },
  {
    id: "mitsubishi",
    en: "Mitsubishi",
    ar: "ميتسوبيشي",
    models: ["Pajero", "Montero Sport", "L200", "ASX", "Attrage", "Outlander", "Eclipse Cross", "Xpander", "Lancer"],
  },
  {
    id: "mazda",
    en: "Mazda",
    ar: "مازدا",
    models: ["Mazda 3", "Mazda 6", "CX-3", "CX-30", "CX-5", "CX-9", "CX-60", "CX-90"],
  },
  {
    id: "volkswagen",
    en: "Volkswagen",
    ar: "فولكس واجن",
    models: ["Jetta", "Passat", "Golf", "Tiguan", "Teramont", "Touareg", "T-Roc"],
  },
  {
    id: "suzuki",
    en: "Suzuki",
    ar: "سوزوكي",
    models: ["Jimny", "Swift", "Dzire", "Vitara", "Grand Vitara", "Ertiga", "Baleno"],
  },
  {
    id: "isuzu",
    en: "Isuzu",
    ar: "إيسوزو",
    models: ["D-Max", "MU-X"],
  },
  {
    id: "mg",
    en: "MG",
    ar: "إم جي",
    models: ["MG5", "MG6", "MG7", "MG GT", "MG ZS", "MG HS", "MG RX5", "MG RX8", "MG One", "Cyberster"],
  },
  {
    id: "changan",
    en: "Changan",
    ar: "شانجان",
    models: ["Alsvin", "Eado", "CS35", "CS35 Plus", "CS55", "CS75", "CS85", "CS95", "UNI-T", "UNI-K", "UNI-V", "Hunter"],
  },
  {
    id: "geely",
    en: "Geely",
    ar: "جيلي",
    models: ["Coolray", "Emgrand", "Azkarra", "Preface", "Monjaro", "Okavango", "Tugella", "Starray"],
  },
  {
    id: "haval",
    en: "Haval",
    ar: "هافال",
    models: ["Jolion", "H6", "H9", "Dargo"],
  },
  {
    id: "chery",
    en: "Chery",
    ar: "شيري",
    models: ["Arrizo 5", "Arrizo 6", "Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8"],
  },
  {
    id: "jetour",
    en: "Jetour",
    ar: "جيتور",
    models: ["Dashing", "X70", "X90", "T2"],
  },
  {
    id: "gac",
    en: "GAC",
    ar: "جي إيه سي",
    models: ["GS3", "GS4", "GS8", "Empow", "GN6"],
  },
  { id: "other", en: "Other", ar: "أخرى", models: [] },
];
